ExWeb3/elixir_ethers

lib/ethers.ex
lib/ethers/contract.ex
lib/ethers/rpc.ex
test/ethers/counter_contract_test.exs
test/ethers/owner_contract_test.exs
test/support/test_rpc_module.ex

`rpc_client` and `rpc_opts` options did not have any effect after the last update.

Fix RPC options and client overriding

---

lib/ethers/types.ex

The `- 1` before doing truncation caused loss of precision.
Fixes #26

Fix Types.max value for larger bitsizes

---

CHANGELOG.md
lib/ethers.ex
test/ethers/counter_contract_test.exs

The functions `Ethers.call/2` and `Ethers.get_logs` now can automatically convert integer block numbers to their equivalent hexadecimal values using `Ethers.Utils.integer_to_hex/1` function.
Closes #31

Automatically convert integer block numbers

---

CHANGELOG.md
lib/ethers.ex
lib/ethers/contract.ex
lib/ethers/contract_helpers.ex
lib/ethers/event_filter.ex
lib/ethers/tx_data.ex
test/ethers/contract_helpers_test.exs
test/ethers/counter_contract_test.exs
test/ethers/event_mixed_index_contract_test.exs
test/ethers/multi_clause_contract_test.exs
test/ethers_test.exs
test/support/contracts/hello_world.sol

Implemented `Ethers.TxData` and `Ethers.EventFilter` structs to help with the development experience of Ethers users.
Both these structs implement Inspect protocol and render nice results when inspected.

Return structs in generated functions and event filters

---

CHANGELOG.md
lib/ethers/tx_data.ex
test/ethers_test.exs
test/support/test_rpc_module.ex

When encoding integers, we used to encode them to their hexadecimal value with 0x prefix when they were part of overrides. But this did not include params as sometimes it makes sense to just manually change/set them.
For example, when we want to move ETH (native currency), somebody might specify it in params like this:
```elixir
Ethers.send(%{value: 1000}, from: "0xab...ef", to: "0xef..ab")
```
If we don't convert `value` to hex then some execution clients will not accept it as it is not per standard.
This PR fixes this issue by converting all integer values to hex.

Fix integer encoding in parameters of transactions

---

CHANGELOG.md
lib/ethers.ex
test/ethers_test.exs

`Ethers.get_balance/2` can be used to query native balance of an account on the chain. This function handles encoding/decoding of the request and makes it easier to use than vanilla `Etheremex.XxxClient.eth_get_balance/3`.

Implement `Ethers.get_balance/2` with tests

---

CHANGELOG.md
lib/ethers.ex
lib/ethers/transaction.ex
test/ethers/transaction_test.exs
test/ethers_test.exs

Per the [conversation](https://github.com/alisinabh/elixir_ethers/pull/74#discussion_r1444148597)
Decode the transaction body, need a bit more discussion.

Decode transaction body

---

lib/ethers/signer/local.ex
lib/ethers/transaction.ex
test/ethers/transaction_test.exs

As discussed with @wchenNL, the `signature_recovery_id` was moved out form transaction struct to reduce confusion.
This also merges `y_parity` and `v` values as they basically always has the same value based on Ethereum execution API specs.
Other than these there are also some generic cleanup in the Transaction module.

Refactor transaction signature functionality

---

CHANGELOG.md
lib/ethers/signer/local.ex
lib/ethers/transaction.ex
test/ethers/transaction_test.exs

We don't need to trim zeros if we:
1. Make sure the transaction data will always be hex encoded starting with '0x' AND
2. Pass them as integers to `ExRLP.encode/1`
Using the existing `trim_leading/1` on all transaction values is dangerous as it can alter the transaction. For example a transaction `data` starting with one or more zero(s) or transaction `to` address which start with one or more zero(s) is perfectly fine. Since ExRLP already handles integers, we need to pass these transaction parameters as integers so we get the correct RLP encoding.
Closes #91

Fix trimmed zeros in transaction encoding

---

CHANGELOG.md
lib/ethers.ex
mix.exs
test/ethers_test.exs

This will be useful in broadcasting signed transactions.

Support signed raw transactions in `Ethers.send/2`

---

lib/ethers/multicall.ex

Decode and aggregate typespecs in Multicall module was incorrect and causing dialyzer error in some projects.

Correct Multicall module typespecs

---

CHANGELOG.md
README.md
lib/ethers/contract.ex
lib/ethers/contracts/erc1155.ex
lib/ethers/contracts/erc165.ex
lib/ethers/contracts/erc721.ex
priv/abi/erc165.json

Closes #108
[EIP-165](https://eips.ethereum.org/EIPS/eip-165) provides a way to check if a contract supports a specific interface or not.
This PR adds:
- Separate `Ethers.Contracts.ERC165` contract
- A behaviour for other contracts supporting ERC165 interface checks to expose their interface ID.
- Support calling  `Ethers.Contracts.ERC165.supports_interface/1` with modules implementing ERC165 behaviour instead of interface IDs directly.

Implement ERC-165 support

---

CHANGELOG.md
lib/ethers.ex
test/ethers_test.exs

Enabling `Ethers.call/2` to be used without the selector makes it easier for users who rely on Ethers configuration to not directly access underlying RPC functionality when they don't have to.

Support raw results in `Ethers.call/2`

---

CHANGELOG.md
lib/ethers/utils.ex

- Handles `nil` result from RPC (FIxes #134)
- Implements an optional backoff

Refactor `Utils.date_to_block_number/3`

---

lib/ethers/transaction.ex
test/ethers/counter_contract_test.exs

Fix hex_decode bug when deploy contract with local signer

Fix transaction hex_decode when deploy with local-signer

---

lib/ethers.ex
lib/ethers/rpc_client.ex
lib/ethers/rpc_client/adapter.ex
lib/ethers/rpc_client/ethereumex_http_client.ex
test/ethers/counter_contract_test.exs

**Why:**
There is an implicit coupling with `ethereumex`, which causes bad decisions to spread from `ethereumex` to `elixir_ethers`, which is not desirable at all.
**How:**
By implementing an adapter for `Ethereumex` that formats and transforms inputs so that they are digested correctly by `ethereumex`.
Resolves: #151

Add Adapter for RPC client

---

CHANGELOG.md
lib/ethers.ex
lib/ethers/contract.ex
lib/ethers/contracts/ens.ex
lib/ethers/name_service.ex
lib/ethers/rpc_client/adapter.ex
lib/ethers/transaction.ex
priv/abi/ens_extended_resolver.json

Improve name service + offchain lookup support

---

CHANGELOG.md
lib/ethers/signer.ex
lib/ethers/signer/local.ex
lib/ethers/transaction.ex
lib/ethers/transaction/eip1559.ex
lib/ethers/transaction/legacy.ex
lib/ethers/transaction/metadata.ex
lib/ethers/transaction/protocol.ex
lib/ethers/transaction/signed.ex
lib/ethers/transaction/signed_transaction.ex
mix.exs
test/ethers/transaction_test.exs
test/ethers_test.exs

Implement `Transaction.decode/1`

---

lib/ethers/utils.ex
test/ethers/utils_test.exs

For implementation there are no breaking changes, and the ERC-1191 encoding is "opt-in" (must be specified by adding `chain_id` param).
closes #146

Add EIP-1191 checksum encoding

---

CHANGELOG.md
lib/ethers/transaction/eip1559.ex
lib/ethers/transaction/eip2930.ex
lib/ethers/transaction/eip4844.ex
lib/ethers/transaction/helpers.ex
lib/ethers/transaction/legacy.ex
lib/ethers/tx_data.ex
test/ethers/tx_data_test.exs

This was no longer needed and is now causing issues when a user wants to specify overrides.

Remove hexification of entries in TxData.to_map/2

---

CONTRIBUTING.md
README.md
test/ethers/ccip_read_test.exs
test/ethers/contract_helpers_test.exs
test/ethers/event_argument_types_contract_test.exs
test/ethers/event_test.exs
test/ethers/multi_clause_contract_test.exs
test/ethers/multicall_test.exs
test/ethers/name_service_test.exs
test/ethers/pay_ether_contract_test.exs
test/ethers/revert_contract_test.exs
test/ethers/signer/local_test.exs
test/ethers/transaction_test.exs
test/ethers/tx_data_test.exs
test/ethers/types_contract_test.exs
test/ethers/types_test.exs
test/ethers_test.exs

improved tests speed
old:
```
Finished in 7.0 seconds (0.00s async, 7.0s sync)
```
new:
```
Finished in 4.9 seconds (2.2s async, 2.7s sync)
```
updated docs because if you run `mix test` you get:
```
== Compilation error in file test/support/contracts.ex ==
** (File.Error) could not read file "tmp/revert_abi.json": no such file or directory
(elixir 1.18.1) lib/file.ex:385: File.read!/1
lib/ethers/contract_helpers.ex:406: Ethers.ContractHelpers.do_read_abi/3
expanding macro: Ethers.Contract.__before_compile__/1
test/support/contracts.ex:4: Ethers.Contract.Test.RevertContract (module)
```
https://github.com/ExWeb3/elixir_ethers/blob/ae8e9ac928a5cdd320369849e0d6460eeb6d5774/mix.exs#L124-L128
i think its because you cannot alias a builtin mix task (`test`)

update docs + improve tests speed

---

lib/ethers/transaction/signed.ex
test/ethers/transaction_test.exs

somehow was not caught in tests :thinking:

fix protocol typo
